### ISSUE TITLE
Verilator Integrations with nMigen | Publishing Html

### ISSUE THREAD

**Issue by BracketMaster** [RobertBaruch/nmigen-tutorial#6]
Hey! These are some fantastic tutorials. I've been working on an nMigen patch that allows verilator to be used as a backend during sim. I came across your fantastic tutorial. I would like to add a section talking about using verilator. Not much changes except passing backend='verilator' to Sim().

Also, may I suggest publishing your markdown as a nice looking website with Sphinx or mkdocs on GitHub io? I could create a branch with the ready to publish generated html from markdown if you are interested. You could have it resolve to nmigen.github.io which might be the most natural thing.

**Comment by BracketMaster** [comment]
Another thought is publishing your tutorial as interactive online with jupyter - something like how chisel-scala HDL did it here:
https://mybinder.org/v2/gh/freechipsproject/chisel-bootcamp/master

Either way - I'd be quite happy to help.

**Comment by XekriRedmane** [comment]
Those are all very interesting ideas! I don't have an objection to a pull request for verilator docs (be sure to include verilator installation instructions/pointers, though). 

Creating docs via mkdocs sounds like a good idea, although nmigen-tutorial.github.io would probaby be better, otherwise I'd be squatting :)

As for jupyter, I've used such notebooks, and I'm not too sure of their utility. It sounds like a lot of work to set up and keep updated, and I'm much more interested in just using nmigen and documenting what I find than trying to keep a notebook up to date as well...
