### ISSUE TITLE
Better verbiage for installing Yosys, SymbiYosys, Yices2, and Boolector

### ISSUE THREAD

**Issue by glanham-jr** [RobertBaruch/nmigen-tutorial#8]
The instructions for installing these dependencies lead to a URL that also contains the [installation instructions](https://symbiyosys.readthedocs.io/en/latest/quickstart.html) for other dependencies. I was under the impression that the following needed to be built to support one another: SymbiYosys, Yices 2, Z3, super_prove, Avy, and Boolector. There could be better verbiage to explicitly state that the other projects do not need to be built.

Additionally, a link to the Yosys, SymbiYosys, Yices2, and Boolector GitHubs could also be provided separately when they were listed. 

EDIT: So after some struggling, I realized that the installation instructions by SymbiYosys do not specify the dependencies needed to install Yosys. By following the [Yosys GitHub](https://github.com/YosysHQ/yosys) instructions I was able to successfully install Yosys. I would say it may be better to use the SymbiYosys instructions as reference, but to follow the installation instruction for each independent project on their own GitHub/GitLab.

**Comment by XekriRedmane** [comment]
I've provided minimal install instructions because installation instructions for subprojects can change at any time, and represents a cognitive load to everyone upstream. That's unfortunate, but currently necessary. I've decided to rely on the SymbiYosys site to provide instructions for SymbiYosys and its dependencies. I've also called out the minimum requirements (yosys, SymbiYosys, yices2, and z3).
